apiVersion: v1
kind: ConfigMap
metadata:
  name: wiz-tasky-aks-config
  namespace: namespace-workflow-1745011064123
  labels:
    app.kubernetes.io/name: wiz-tasky-aks
    kubernetes.azure.com/generator: devhub
data: