apiVersion: v1
kind: Service
metadata:
  name: tasky
  namespace: tasky
  labels:
    app.kubernetes.io/name: tasky
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: tasky
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
