apiVersion: v1
kind: Service
metadata:
  name: wiz-tasky-aks
  namespace: namespace-workflow-1745011064123
  labels:
    app.kubernetes.io/name: wiz-tasky-aks
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: wiz-tasky-aks
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080